# Generated by Django 4.1 on 2022-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sub', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
